'use strict';
const {JSDOM,VirtualConsole}=require('jsdom'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const mock=require('./vehicles-mock.cjs'),root=path.join(__dirname,'..');
const tick=()=>new Promise(resolve=>setTimeout(resolve,30));
async function open(file,scenario={}){
  const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!/Not implemented/.test(e.message))errors.push(e.message);});
  const dom=new JSDOM(fs.readFileSync(path.join(root,file),'utf8'),{url:'http://localhost/'+file,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc}),w=dom.window;
  w.matchMedia=()=>({matches:false,addEventListener:()=>{}});w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.confirm=()=>true;
  w.eval('('+mock.toString()+')('+JSON.stringify(scenario)+')');
  for(const node of w.document.querySelectorAll('script')){const src=node.getAttribute('src');if(src&&!src.startsWith('https://'))w.eval(fs.readFileSync(path.join(root,src.split('?')[0]),'utf8'));else if(!src)w.eval(node.textContent);}
  await tick();return {w,dom,errors};
}
(async()=>{
  let checked=0;
  let {w,errors}=await open('fahrzeuge.html');assert.equal(w.document.querySelectorAll('.vehicle-card').length,1);assert(w.document.getElementById('vehicleList').textContent.includes('123'));assert(!w.document.getElementById('addVehicle').hidden);
  w.document.querySelector('[data-action=start]').click();await tick();assert.equal(w.vehicleCalls[0].values.action,'start');assert(w.document.querySelector('[data-action=free]'));assert(!w.document.querySelector('[data-action=day]'));w.document.querySelector('[data-action=free]').click();await tick();assert(w.document.querySelector('[data-action=start]'));assert.deepEqual(errors,[]);w.close();checked++;
  ({w,errors}=await open('fahrzeuge.html',{vehicles:{first:{name:'Erster',plate:'FR 1',km:1,revision:1,active:{uid:'worker',name:'Max Muster'}},second:{name:'Zweiter',plate:'FR 2',km:2,revision:0,active:null},third:{name:'Dritter',plate:'FR 3',km:3,revision:1,active:{uid:'other',name:'Andere Person'}}}}));
  assert(w.document.querySelector('[data-action=start]').disabled);assert(w.document.querySelector('[data-action=day]').disabled);assert(w.document.querySelector('[data-action=takeover]').disabled);assert(!w.document.querySelector('[data-action=free]').disabled);assert.deepEqual(errors,[]);w.close();checked++;
  ({w,errors}=await open('fahrzeuge.html',{permissions:{fahrzeuge:'view',fahrzeugeErstellen:'none'}}));assert(!w.document.querySelector('[data-action=start]'));assert(!w.document.querySelector('[data-action=fuel]'));assert(w.document.querySelector('[data-action=favorite]'));assert(w.document.getElementById('addVehicle').hidden);assert(w.document.getElementById('accessReadOnly'));assert.deepEqual(errors,[]);w.close();checked++;
  ({w,errors}=await open('fahrzeuge.html'));w.document.querySelector('[data-action=fuel]').click();assert(w.document.getElementById('vehicleDialog').open);const input=w.document.querySelector('[name=km]');assert.equal(input.value,'');w.document.getElementById('vehicleForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.equal(w.vehicleCalls.length,0);input.value='123500';w.document.getElementById('vehicleForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.equal(w.vehicleCalls[0].values.km,123500);assert.equal(w.document.getElementById('vehicleDialog').open,false);assert(w.document.querySelector('.vehicle-km strong').textContent.includes('500'));assert.deepEqual(errors,[]);w.close();checked++;
  ({w,errors}=await open('fahrzeuge.html',{vehicles:{bus:{name:'Bus',plate:'FR 123',km:100,revision:1,active:{uid:'other',name:'Anna'}}}}));w.document.querySelector('[data-action=takeover]').click();assert(w.document.getElementById('dialogNote').textContent.includes('Anna'));w.document.getElementById('vehicleForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.equal(w.vehicleCalls[0].values.action,'takeover');assert(w.document.querySelector('[data-action=free]'));assert.deepEqual(errors,[]);w.close();checked++;
  ({w,errors}=await open('fahrzeuge.html'));w.document.querySelector('[data-action=favorite]').click();await tick();assert.equal(w.document.querySelector('[data-action=favorite]').getAttribute('aria-pressed'),'true');w.document.getElementById('onlyFavorites').checked=true;w.document.getElementById('onlyFavorites').dispatchEvent(new w.Event('change'));assert.equal(w.document.querySelectorAll('.vehicle-card').length,1);w.document.querySelector('[data-action=favorite]').click();await tick();assert.equal(w.document.querySelectorAll('.vehicle-card').length,0);assert.deepEqual(errors,[]);w.close();checked++;
  ({w,errors}=await open('meine-uebersicht.html',{favorites:['bus']}));assert(!w.document.getElementById('myVehiclesSection').hidden);assert.equal(w.document.getElementById('vehicleCount').textContent,'1');assert(w.document.querySelector('[data-action=start]'));w.setVehicle('bus',{active:{uid:'other',name:'Anna'}});await tick();assert(w.document.getElementById('vehicleList').textContent.includes('Anna'));w.document.querySelector('[data-action=takeover]').click();w.document.getElementById('vehicleForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert(w.document.querySelector('[data-action=free]'));assert.deepEqual(errors,[]);w.close();checked++;
  ({w,errors}=await open('fahrzeuge.html',{actionError:'Gerade geändert'}));w.document.querySelector('[data-action=day]').click();w.document.getElementById('vehicleForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert(w.document.getElementById('dialogSave').disabled);assert(!w.document.getElementById('dialogCancel').disabled);assert(w.document.getElementById('dialogStatus').textContent.includes('nochmals'));assert.deepEqual(errors,[]);w.close();checked++;
  ({w,errors}=await open('meine-uebersicht.html',{favorites:['bus'],vehicles:{bus:{name:'Favorit',plate:'FR 1',km:100,revision:0,active:null},other:{name:'Nicht Favorit',plate:'FR 2',km:200,revision:1,active:{uid:'worker',name:'Max Muster'}}}}));assert.equal(w.document.querySelectorAll('.vehicle-card').length,1);assert(w.document.querySelector('[data-action=start]').disabled);assert(w.document.querySelector('[data-action=day]').disabled);assert.deepEqual(errors,[]);w.close();checked++;
  ({w,errors}=await open('fahrzeuge.html',{permissions:{fahrzeugeUebernehmen:'none'},vehicles:{bus:{name:'Bus',plate:'FR 123',km:100,revision:1,active:{uid:'other',name:'Anna'}}}}));assert(!w.document.querySelector('[data-action=takeover]'));assert(w.document.querySelector('[data-action=fuel]'));assert.deepEqual(errors,[]);w.close();checked++;
  console.log('Passed '+checked+' vehicle DOM integration scenarios.');
})().catch(error=>{console.error(error);process.exitCode=1;});
